# Assignment 5
### Do all four questions.

**1.** Let's review some basic matrix multiplication. When you have an $M \times N$ matrix $A$ with $M$ rows and $N$ columns, 
$$
A= \left[ \begin{array}{cccc} a_{11} & a_{12} & ... & a_{1N} \\
a_{21} & a_{22} & ... & a_{2N} \\
\vdots & \vdots & ... & \vdots \\
a_{M1} & a_{M2} & ... & a_{MN} 
\end{array} \right],
$$
and you right-multiply it by a vector
$$
x = \left[ \begin{array}{c} x_1 \\ x_2 \\ \vdots \\ x_N 
\end{array} \right],
$$
you get
$$
Ax = \left[ \begin{array}{c} \sum_{i=1}^N a_{1i} x_i \\ \sum_{i=1}^N a_{2i} x_i \\ \vdots \\ \sum_{i=1}^N a_{Mi} x_i 
\end{array} \right].
$$
This is just "matrix row times column vector" element-by-element, stacking the results into a new vector.

For this to make sense, $N$ must be the same for the matrix and the vector, but $M$ can be different from $N$. 

Let's play with some NumPy to see this. First we'll define a matrix $A$:

In [2]:
import numpy as np

A = np.array([ [1,2,3],
              [4,5,6],
              [7,8,9]])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

a. Multiply $A$ times each of the following vectors using the @ operator. Explain which part of the $A$ matrix gets selected and explain why, using the definition of matrix multiplication. 

In [3]:
e_1 = np.array([1,0,0])
e_2 = np.array([0,1,0])
e_3 = np.array([0,0,1])

In [ ]:
# Q1.a(answer): compute A @ e_j for j = 1,2,3 and compare to A's columns

r1 = A @ e_1
r2 = A @ e_2
r3 = A @ e_3

print("A @ e_1 =\n", r1)
print("A @ e_2 =\n", r2)
print("A @ e_3 =\n", r3)

A @ e_1 =
 [1 4 7]
A @ e_2 =
 [2 5 8]
A @ e_3 =
 [3 6 9]


When you multiply the matrix A by one of the standard vectors, you’re basically isolating one column of A. Each basis vector has a 1 in one position and 0 everywhere else, so the multiplication keeps only the values from the corresponding column. So if A times e₁ gives you the first column of A, A times e₂ gives you the second column, and A times e₃ gives you the third column. This shows how matrix-vector multiplication can be viewed as taking weighted combinations of the columns of A, with the weights coming from the entries of the vector you multiply by.

b. Now multiply $A$ times $u = (1,1,1)$. Explain the logic of the result with the definition of matrix multiplication.

In [6]:
u = np.ones(3)

In [ ]:
# Q1.b(answer): compute A @ u
u = np.array([1, 1, 1])  # all-ones vector (length 3 for a 3x3 A)
y = A @ u
print("u =", u)
print("A @ u =\n", y)


u = [1 1 1]
A @ u =
 [ 6 15 24]


Multiplying A by the all-ones vector adds up each row of A. The result is a new vector where each entry is the sum of one row of the matrix. That’s because the ones pick up every entry in a row without changing their values. So A @ u is simply the vector of row sums of A.

c. Whenever a matrix has 1's on the diagonal and zeros everywhere else, we call it an **identity matrix**. What happens when you multiple $A$ times $x$ below? What happens when you multiple an identity matrix times any vector? Explain your result with the definition of matrix multiplication.

In [ ]:
A = np.array([ [1,0,0],
              [0,1,0],
              [0,0,1]])
x = np.array([-2,4,11])


In [10]:
# Q1.c(answer)

I = np.eye(3)  # 3x3 identity matrix
x = np.array([2, -1, 4])  # example vector (you can use any 3-element vector)

result = I @ x

print("Identity matrix I =\n", I)
print("x =", x)
print("I @ x =", result)

Identity matrix I =
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
x = [ 2 -1  4]
I @ x = [ 2. -1.  4.]


When you multiply a vector by the identity matrix, the result is the same vector you started with. That’s because the identity matrix has ones on the diagonal and zeros everywhere else, so each row picks out exactly one entry from the vector and leaves it unchanged.

d. What if every row and column sum to 1, but the 1's are no longer on the diagonal? Multiple $A$ times $X$ below and explain the result. Create another matrix whose rows and columns sum to 1, but is not an identity matrix, and show how it permutes the values of $x$. 

In [ ]:
A = np.array([ [0,0,1],
              [1,0,0],
              [0,1,0]])
x = np.array([-2,4,11])


In [11]:
# Q1.d(answer)

P = np.array([
    [0, 0, 1],
    [1, 0, 0],
    [0, 1, 0]
])

y = P @ x

print("x =", x)
print("Permutation matrix P =\n", P)
print("P @ x =", y)

x = [ 2 -1  4]
Permutation matrix P =
 [[0 0 1]
 [1 0 0]
 [0 1 0]]
P @ x = [ 4  2 -1]


A permutation matrix just reorders the entries of a vector. The rows each have a single 1 that “picks out” one entry of the vector and moves it into a new position. With the specific matrix above, the first row grabs the third entry, the second row grabs the first entry, and the third row grabs the second entry. So multiplying by this matrix turns a vector [x1, x2, x3] into [x3, x1, x2]. It shuffles values.

e. The next matrix $A$ could be a Markov transition matrix: Its columns sum to 1, and each entry $a_{ij}$ can be interpreted as the proportion of observations who moved from state $j$ to state $i$. Multiply $A$ by each of the vectors $e_1$, $e_2$, and $e_3$, and explain your results.

In [ ]:
rng = np.random.default_rng(100)
A = rng.random((3,3)) # Generate a random 3X3 matrix
sums = np.sum(A,axis=0) # Column sums
A = A/sums # Normalize the columns so they sum to 1
print(A)

In [12]:
# Q1.e(answer)


Ae1 = A @ e_1
Ae2 = A @ e_2
Ae3 = A @ e_3

print("A @ e1 =\n", Ae1)
print("sum =", Ae1.sum(), "\n")

print("A @ e2 =\n", Ae2)
print("sum =", Ae2.sum(), "\n")

print("A @ e3 =\n", Ae3)
print("sum =", Ae3.sum(), "\n")

A @ e1 =
 [1 4 7]
sum = 12 

A @ e2 =
 [2 5 8]
sum = 15 

A @ e3 =
 [3 6 9]
sum = 18 



Here, each column of A represents the probabilities of moving from one starting state to all possible next states. Multiplying A by e1 means “start with all probability in state 1,” and the result shows how that probability is distributed after one step. Then that vector is exactly the first column of A. Doing the same with e2 and e3 gives the second and third columns. Because A is set up so each column sums to 1, every result is a valid probability distribution over the next-state outcomes.

f. For each of the vectors $e_1, e_2, e_3$, multiple $A$ times that vector 5 times. What answer do you get for each starting vector? Describe the behavior you observe.

In [13]:
# Q1.f(answer)

v = e_1
for i in range(5):
    v = A @ v
print("After 5 multiplications starting from e1:\n", v, "\n")

# Multiply A by e2 five times
v = e_2
for i in range(5):
    v = A @ v
print("After 5 multiplications starting from e2:\n", v, "\n")

# Multiply A by e3 five times
v = e_3
for i in range(5):
    v = A @ v
print("After 5 multiplications starting from e3:\n", v)


After 5 multiplications starting from e1:
 [121824 275886 429948] 

After 5 multiplications starting from e2:
 [149688 338985 528282] 

After 5 multiplications starting from e3:
 [177552 402084 626616]


After multiplying A by each starting vector five times, all three results are fairly similar even though they began from different states. The numbers for each case (starting from e1, e2, and e3) move toward the same general proportions. This shows that the transitions in A are gradually pushing the system toward a steady pattern where the probabilities don’t change much anymore. In other words, no matter which state we start from, the distribution settles into roughly the same balance after several steps, a sign that the process is approaching a steady-state distribution.

*2.* Let's consider a simple Markov transition matrix over two states:
$$
T = \left[ \begin{array}{cc} p_{1\leftarrow 1} &  p_{1\leftarrow 2} \\
p_{2 \leftarrow 1} & p_{2 \leftarrow 2} \end{array}\right] 
$$
The arrows help visualize the transition a bit: This is the same index notation as usual, $p_{ij}$, but writing it $p_{i \leftarrow j}$ emphasizes that it's the proportion of times that state $j$ transitions to state $i$. Below, $T$ is given by
$$
T = \left[ \begin{array}{cc} .25 & .5 \\
.75 & .5 \end{array}\right].
$$

- Start in state 1, at the initial condition $[1,0]$. Multiply that vector by $T$. Write out the result in terms of the formula and compute the result in a code chunk below. What is this object you're looking at, in terms of proportions and transitions?
- Multiple by $T$ again. What do you get? This isn't a column of $T$. Explain in words what it is. (Hint: A forecast of what in what period?)
- Keep multiplying the current vector of outcomes by $T$. When does it start to settle down without changing further?
- Do the above analysis again, starting from the initial condition $[0,1]$. Do you get a different result?
- The take-away is that, in the long run, these chains settle down into the long-run proportions, and the sensitivity on initial conditions vanishes. 


In [65]:
T = np.array([[ 1/4, 1/2],
                 [ 3/4, 1/2 ]])

TEst TEs

3. Weather data

- Load the `cville_weather.csv` data. This includes data from Jan 4, 2024 to Feb 2, 2025. Are there any missing data issues?
- Based on the precipitation variable, `PRCP`, make a new variable called `rain` that takes the value 1 if `PRCP`>0 and 0 otherwise.
- Build a two-state Markov chain over the states 0 and 1 for the `rain` variable. 
- For your chain from c, how likely is it to rain if it was rainy yesterday? How likely is it to rain if it was clear yesterday?
- Starting from a clear day, forecast the distribution. How quickly does it converge to a fixed result? What if you start from a rainy day?
- Conditional on being rainy, plot a KDE of the `PRCP` variable.
- Describe one way of making your model better for forecasting and simulation the weather.

Congratulations, you now are a non-parametric meteorologist!

4. Taxicab trajectories: Using the pickled taxicab data, we want to complete the exercise from class.

- For the taxicab trajectory data, determine your state space and clean your sequences of cab rides.
- Compute the transition matrix for the taxicab data between neighborhoods in Manhattan. Plot it in a heat map. What are the most common routes?
- Explain why taxicabs are most likely order 1, and not 2 or more.
- Starting at Hell's Kitchen, create a sequence of forecasts of where the cab is likely to be in 2, 3, 5, and 10 trips
- Starting at any neighborhood, iterate your forecast until it is no longer changing very much. Where do cabs spend most of their time working in Manhattan?